### ISSUE TITLE
Add 2D renderer support

### ISSUE THREAD

**Issue by Zallist** [Zallist/unity-universal-shadergraph-extensions#9]
Right now the 2D renderer is just using the PBR2DRenderer.hlsl pathway, which is not the Simple Lit one. Someone needs to swap that for a 2D one based on the existing `Simple Lit.shader` 2D pass, in the same way, and then change the C# code to reference the new .hlsl file.

If I get any interest on this, I'll probably do it myself.

**Comment by bmourit** [comment]
The PBR2dPass.hlsl does the exact same thing as we would need for SimpleLit. The naming is confusing though, since there is nothing specific to PBR about it. The regular uber shaders both (Lit/SimpleLit) use Universal2d.hlsl. That is basically what this file is replacing in Shader Graph.

Ideally, if Unity decided to merge this, they would rename the PBR2dPass to something more generic (Universal2dPass?) for clarity.
I don't see a benefit in duplicating the code in a new file though, since PBR2dPass will still be setup properly for SimpleLit.

**Comment by Zallist** [comment]
That's what I get for not even looking at the underlying code.
Thanks for checking.
